name: Publish Packages to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "tag=1.0.${{ github.run_number }}.$(git rev-parse --short HEAD)-SNAPSHOT" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish Packages
        run: ./gradlew common:publishCommonPublicationToGitHubPackagesRepository catalog:publishCatalogPublicationToGitHubPackagesRepository bom:publishBOMPublicationToGitHubPackagesRepository
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVISION: ${{ steps.vars.outputs.tag }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
